### ISSUE TITLE
No login possible

### ISSUE THREAD

**Issue by jgrete** [YunoHost-Apps/ulogger_ynh#5]
Hi,
after installation under YunoHost (3.6.5.1), I'm not able to login ("Wrong username or password". nor with the single existing user credentials neither with the admin credentials).
What did I miss? Any "special" account to use?
Regards
Jürgen

**Comment by Schdefoon** [comment]
Hi Jürgen,
was searching for help here, because I had the same problem.
In the meantime I could fix it by editing /var/www/ulogger/config.php
In line 46 I set require_authentification to 0.
Seems like yunohost sso is still working with this settings. In my test another yunohost user that had no permission for ulogger couldn't get into ulogger.

Now I'm looking for a way to import a gpx file. This is listed in the features, but there seems to be no button for this...

Regards Stefan

**Comment by Schdefoon** [comment]
Found the correct way in the meantime:
Run https://"path-to-yunohost-server"/ulogger/scripts/setup.php and create a user.
The created user has the possibility to import gpx files :-)

**Comment by jgrete** [comment]
Using that path I'm getting a 404 :-(

**Comment by Schdefoon** [comment]
You should not get a 404...
Did you replace "path-to-yunohost-server" with your server path?
For me the correct address is https://yunohost.local/ulogger/scripts/setup.php
But this is not necessarily the correct address of your YunoHost server.

**Comment by jgrete** [comment]
Hi,
i cannot replace "path-to-yunoshost-server" because "This feature hasn't been implemented yet" po-up appears as soon as I try to click the  button...
@Schdefoon: Adapted to my base url I'm ending up at the yunoshost entry page (with all the other apps)

**Comment by Schdefoon** [comment]
> Adapted to my base url I'm ending up at the yunoshost entry page (with all the other apps)

I guess you weren't logged in so you your browser redirected you to the login page.

So here's another try:

- Call (again adapted to your base url) https://yunohost.local/sso
- You should see a login page
- Insert your username and password and continue
- You should see all of your apps like before
- Don't close your browser - just continue
- Now call (again adapted to your base url) https://yunohost.local/ulogger/scripts/setup.php
- You should see a "welcome to ulogger" page with some instructions to continue

It is just the same like before but you call the setup-page **after** your successful login

**Comment by jgrete** [comment]
[y]     Call (again adapted to your base url) https://yunohost.local/sso
 [y]     You should see a login page
 [y]     Insert your username and password and continue
 [y]     You should see all of your apps like before
 [y]     Don't close your browser - just continue
 [*]     Now call (again adapted to your base url) https://yunohost.local/ulogger/scripts/setup.php
 [**]    You should see a "welcome to ulogger" page with some instructions to continue

* Result: Back on the apps page
** No - my ulogger url is <host>/yunohost/ulogger/...
because I can't change the base url (see above) like in other apps. I need to do that, because I'm using a reverse proxy to access yunohost.

**Comment by Schdefoon** [comment]
I'm sorry that this is not working for you and I have no idea any more how to help you.
For me this help worked: https://github.com/bfabiszewski/ulogger-server#install (the first three steps can be skipped since YunoHost already managed this for you). You should find the files that are mentioned in /var/www/ulogger
But if you can't call the setup script then it's hard to get it running ...

**Comment by jgrete** [comment]
@Schdefoon 
Ok, maybe it will work some day
Anyway - thanks a lot for your time
